# Generated by Django 5.1.3 on 2025-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDCapp', '0002_alter_cashflow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
